# -*- coding: utf-8 -*-
"""2000sampleSignLanguage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAjWGDb4uXW-9ihYiSyr9scpPyg8raZM

**STEP 1: Setup YOLOv5 Environment**
"""

# Commented out IPython magic to ensure Python compatibility.
# Clone YOLOv5 repository and install requirements
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
# %pip install -qr requirements.txt
import torch
from IPython.display import Image, clear_output

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

"""**STEP 2: Download the Kaggle Dataset**

You will need your kaggle.json file (from Kaggle Account Settings). This code uploads your key and downloads the specific dataset you found.

**Steps to Get your Kaggle API Token**

1. Go to Kaggle and log in.
2. Click on your profile picture (top right) Settings.
3. Scroll down to the API section and click Create New Legacy API Token.
4. This will download a file named kaggle.json. Keep this file ready.
"""

from google.colab import files
files.upload()  # Upload your kaggle.json here

# Setup Kaggle API
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download and unzip the sign language dataset
!kaggle datasets download -d harshvardhan21/sign-language-detection-using-images
!unzip -o sign-language-detection-using-images.zip -d /content/raw_data

"""**STEP 3: Auto-Labelling**

Transforms the folder-based Kaggle data into the image+label format required by YOLOv5.

"""

# Step #3: Stratified Sampling (100 images per class to reach 2k training samples)
import os
import random
from PIL import Image

raw_dir = '/content/raw_data/data'
processed_dir = '/content/sign_lang_yolo'
classes = sorted(os.listdir(raw_dir))

# Create YOLO directory structure
for split in ['train', 'val']:
    for folder in ['images', 'labels']:
        os.makedirs(os.path.join(processed_dir, split, folder), exist_ok=True)

# Process exactly 100 images per class to yield ~2,000+ training images total
for idx, cls in enumerate(classes):
    cls_path = os.path.join(raw_dir, cls)
    all_imgs = [f for f in os.listdir(cls_path) if f.endswith(('.jpg', '.png', '.jpeg'))]

    # CHANGED: Increased from 60 to 100 to scale total training pool up
    sample_size = min(100, len(all_imgs))
    sampled_imgs = random.sample(all_imgs, sample_size)

    # 80% train (80 images), 20% val (20 images) per class
    split_pt = int(sample_size * 0.8)

    for i, img_name in enumerate(sampled_imgs):
        subset = 'train' if i < split_pt else 'val'

        # Copy image and create .txt label
        with Image.open(os.path.join(cls_path, img_name)) as img:
            new_name = f"{cls}_{img_name}"
            img.save(os.path.join(processed_dir, subset, 'images', new_name))

            label_path = os.path.join(processed_dir, subset, 'labels', new_name.rsplit('.', 1)[0] + '.txt')
            with open(label_path, 'w') as f:
                f.write(f"{idx} 0.5 0.5 0.8 0.8") # <class> <x> <y> <w> <h>

print(f"Dataset preparation complete. Limited to 100 images per class across {len(classes)} classes.")

"""**STEP 4: Create Configuration YAML**

Tells the *train.py* script where your data lives and what the letters are.

"""

import os
import random

train_path = '/content/sign_lang_yolo/train/images'
all_images = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith(('.jpg', '.png', '.jpeg'))]

# This will now successfully grab exactly 2,000 images because len(all_images) > 2000
subset_count = min(2000, len(all_images))
subset_images = random.sample(all_images, subset_count)

# Save these paths to a text file
subset_file = '/content/sign_lang_yolo/train_subset.txt'
with open(subset_file, 'w') as f:
    for img_path in subset_images:
        f.write(img_path + '\n')

print(f"Created subset list with {subset_count} images at {subset_file}")

"""**STEP 5: Training Command**

Run the training using Small variant (yolov5s.pt)
"""

import os
import random
import yaml


# 2. Setup Paths
train_path = '/content/sign_lang_yolo/train/images'
val_path = '/content/sign_lang_yolo/val/images'

# 3. Helper to create subset lists2
def create_subset(src_path, filename, count):
    all_imgs = [os.path.join(src_path, f) for f in os.listdir(src_path) if f.endswith(('.jpg', '.png', '.jpeg'))]
    subset = random.sample(all_imgs, min(count, len(all_imgs)))
    with open(filename, 'w') as f:
        for img in subset:
            f.write(img + '\n')
    return os.path.abspath(filename)

# CHANGED: Update subset creation to 2000 for training, and 200 for validation
train_list = create_subset(train_path, 'subset_train.txt', 2000)
val_list = create_subset(val_path, 'subset_val.txt', 200)

# 2. Update YAML (Ensure 'classes' is defined earlier in your notebook)
config = {
  'train': train_list,
  'val': val_list,
  'nc': len(classes),
  'names': classes
}

# Fix: Save data.yaml to the correct directory where train.py expects it
with open('data.yaml', 'w') as f:
    yaml.dump(config, f)

# 3. Optimized Training Command
# NOTE: If you hit an out-of-memory error, change "--batch 32" to "--batch 16"
!python train.py --img 416 --batch 32 --epochs 100 --data data.yaml --weights yolov5s.pt --workers 4

#prototype
#!python train.py --img 640 --batch 16 --epochs 5 --data data.yaml --weights yolov5s.pt

"""**STEP 6: Evaluation and Inference**

Check the performance and test the model on images it has never seen.
"""

import IPython
import os

# Display training results
results_image_path = 'runs/train/exp/results.png'
if os.path.exists(results_image_path):
    print(f"Displaying training results from {results_image_path}")
    IPython.display.Image(filename=results_image_path, width=1000)
else:
    print(f"Warning: Training results image '{results_image_path}' not found. "
          "This typically happens if the training in the previous step did not complete successfully.")

# Run detection on test images
!python detect.py --weights runs/train/exp/weights/best.pt --img 416 --conf 0.25 --source /content/sign_lang_yolo/val/images

import os
from IPython.display import Image

detection_results_dir = 'runs/detect/exp'

# List contents of the detection results directory
print(f"Contents of '{detection_results_dir}':")
for item in os.listdir(detection_results_dir):
    print(item)

# Display a sample detected image (assuming there's at least one .jpg or .png file)
# You might need to adjust this to pick a specific image if there are many
image_files = [f for f in os.listdir(detection_results_dir) if f.endswith(('.jpg', '.png', '.jpeg'))]

if image_files:
    sample_image_path = os.path.join(detection_results_dir, image_files[0])
    print(f"\nDisplaying a sample detected image: {sample_image_path}")
    Image(filename=sample_image_path, width=800)
else:
    print("No image files found in the detection results directory to display.")

"""STEP 7: Graph"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the results CSV file
results_path = 'runs/train/exp/results.csv'
results_df = pd.read_csv(results_path)

# Clean column names (remove leading spaces if present)
# The original YOLOv5 results.csv can sometimes have a leading space, this ensures they are clean
results_df.columns = results_df.columns.str.strip()

# Plotting training metrics
plt.figure(figsize=(15, 5))

# Subplot for Precision and Recall
plt.subplot(1, 3, 1)
sns.lineplot(data=results_df, x='epoch', y='metrics/precision')
sns.lineplot(data=results_df, x='epoch', y='metrics/recall')
plt.title('Precision and Recall vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Value')
plt.legend(['Precision', 'Recall'])
plt.grid(True)

# Subplot for mAP_0.5
plt.subplot(1, 3, 2)
sns.lineplot(data=results_df, x='epoch', y='metrics/mAP_0.5')
plt.title('mAP@0.5 vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('mAP@0.5')
plt.grid(True)

# Subplot for mAP_0.5:0.95
plt.subplot(1, 3, 3)
sns.lineplot(data=results_df, x='epoch', y='metrics/mAP_0.5:0.95')
plt.title('mAP@0.5:0.95 vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('mAP@0.5:0.95')
plt.grid(True)

plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')